spring.application.name=api-app


spring.datasource.url=jdbc:postgresql://localhost:5432/booksdb
spring.datasource.username=apple
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

spring.ai.deepseek.api-key=
spring.profiles.active=local